/* generated GL stub surface - headless satisfaction only */
void* glActiveTexture(void){ return 0; }
void* glAttachShader(void){ return 0; }
void* glBegin(void){ return 0; }
void* glBeginQuery(void){ return 0; }
void* glBindBuffer(void){ return 0; }
void* glBindBufferBase(void){ return 0; }
void* glBindFramebuffer(void){ return 0; }
void* glBindImageTexture(void){ return 0; }
void* glBindRenderbuffer(void){ return 0; }
void* glBindSampler(void){ return 0; }
void* glBindTexture(void){ return 0; }
void* glBindTransformFeedback(void){ return 0; }
void* glBindVertexArray(void){ return 0; }
void* glBlendEquation(void){ return 0; }
void* glBlendEquationSeparate(void){ return 0; }
void* glBlendFunc(void){ return 0; }
void* glBlendFuncSeparate(void){ return 0; }
void* glBlitFramebuffer(void){ return 0; }
void* glBufferData(void){ return 0; }
void* glBufferSubData(void){ return 0; }
void* glCheckFramebufferStatus(void){ return 0; }
void* glClear(void){ return 0; }
void* glClearColor(void){ return 0; }
void* glClearDepth(void){ return 0; }
void* glClearDepthf(void){ return 0; }
void* glClearStencil(void){ return 0; }
void* glClientWaitSync(void){ return 0; }
void* glColor3f(void){ return 0; }
void* glColor3ub(void){ return 0; }
void* glColor4f(void){ return 0; }
void* glColorMask(void){ return 0; }
void* glColorPointer(void){ return 0; }
void* glCompileShader(void){ return 0; }
void* glCompressedTexImage2D(void){ return 0; }
void* glCompressedTexSubImage2D(void){ return 0; }
void* glCopyTexImage2D(void){ return 0; }
void* glCreateProgram(void){ return 0; }
void* glCreateShader(void){ return 0; }
void* glCullFace(void){ return 0; }
void* glDeleteBuffers(void){ return 0; }
void* glDeleteFramebuffers(void){ return 0; }
void* glDeleteProgram(void){ return 0; }
void* glDeleteQueries(void){ return 0; }
void* glDeleteRenderbuffers(void){ return 0; }
void* glDeleteSamplers(void){ return 0; }
void* glDeleteShader(void){ return 0; }
void* glDeleteSync(void){ return 0; }
void* glDeleteTextures(void){ return 0; }
void* glDeleteVertexArrays(void){ return 0; }
void* glDepthFunc(void){ return 0; }
void* glDepthMask(void){ return 0; }
void* glDepthRange(void){ return 0; }
void* glDepthRangef(void){ return 0; }
void* glDisable(void){ return 0; }
void* glDisableClientState(void){ return 0; }
void* glDisableVertexAttribArray(void){ return 0; }
void* glDispatchCompute(void){ return 0; }
void* glDispatchComputeIndirect(void){ return 0; }
void* glDrawArrays(void){ return 0; }
void* glDrawBuffer(void){ return 0; }
void* glDrawBuffers(void){ return 0; }
void* glDrawElements(void){ return 0; }
void* glDrawRangeElements(void){ return 0; }
void* glEGLImageTargetTexture2DOES(void){ return 0; }
void* glEnable(void){ return 0; }
void* glEnableClientState(void){ return 0; }
void* glEnableVertexAttribArray(void){ return 0; }
void* glEnd(void){ return 0; }
void* glEndQuery(void){ return 0; }
void* glFenceSync(void){ return 0; }
void* glFinish(void){ return 0; }
void* glFlush(void){ return 0; }
void* glFlushMappedBufferRange(void){ return 0; }
void* glFramebufferRenderbuffer(void){ return 0; }
void* glFramebufferTexture2D(void){ return 0; }
void* glFrontFace(void){ return 0; }
void* glFrustum(void){ return 0; }
void* glGenBuffers(void){ return 0; }
void* glGenFramebuffers(void){ return 0; }
void* glGenQueries(void){ return 0; }
void* glGenRenderbuffers(void){ return 0; }
void* glGenSamplers(void){ return 0; }
void* glGenTextures(void){ return 0; }
void* glGenTransformFeedbacks(void){ return 0; }
void* glGenVertexArrays(void){ return 0; }
void* glGetActiveAttrib(void){ return 0; }
void* glGetActiveUniform(void){ return 0; }
void* glGetAttribLocation(void){ return 0; }
void* glGetBinaryLength(void){ return 0; }
void* glGetBooleanv(void){ return 0; }
void* glGetCompressedTexImage(void){ return 0; }
void* glGetDoublev(void){ return 0; }
void* glGetError(void){ return 0; }
void* glGetFloatv(void){ return 0; }
void* glGetFramebufferAttachmentParameteriv(void){ return 0; }
void* glGetGraphicsResetStatus(void){ return 0; }
void* glGetIntegerv(void){ return 0; }
void* glGetPointerv(void){ return 0; }
void* glGetProgramBinary(void){ return 0; }
void* glGetProgramInfoLog(void){ return 0; }
void* glGetProgramiv(void){ return 0; }
void* glGetQueryObjectuiv(void){ return 0; }
void* glGetShaderInfoLog(void){ return 0; }
void* glGetShaderPrecisionFormat(void){ return 0; }
void* glGetShaderiv(void){ return 0; }
void* glGetString(void){ return 0; }
void* glGetStringi(void){ return 0; }
void* glGetTexImage(void){ return 0; }
void* glGetTexLevelParameteriv(void){ return 0; }
void* glGetUniformBlockIndex(void){ return 0; }
void* glGetUniformLocation(void){ return 0; }
void* glGetnUniformfv(void){ return 0; }
void* glHint(void){ return 0; }
void* glInvalidateBufferData(void){ return 0; }
void* glIsBuffer(void){ return 0; }
void* glIsEnabled(void){ return 0; }
void* glIsFramebuffer(void){ return 0; }
void* glIsRenderbuffer(void){ return 0; }
void* glIsTexture(void){ return 0; }
void* glLineWidth(void){ return 0; }
void* glLinkProgram(void){ return 0; }
void* glLoadIdentity(void){ return 0; }
void* glLogicOp(void){ return 0; }
void* glMapBuffer(void){ return 0; }
void* glMapBufferRange(void){ return 0; }
void* glMatrixMode(void){ return 0; }
void* glMemoryBarrier(void){ return 0; }
void* glNormal3f(void){ return 0; }
void* glNormalPointer(void){ return 0; }
void* glOrtho(void){ return 0; }
void* glPixelStorei(void){ return 0; }
void* glPixelZoom(void){ return 0; }
void* glPointSize(void){ return 0; }
void* glPolygonMode(void){ return 0; }
void* glPopMatrix(void){ return 0; }
void* glProgramBinary(void){ return 0; }
void* glPushMatrix(void){ return 0; }
void* glRasterPos2f(void){ return 0; }
void* glReadBuffer(void){ return 0; }
void* glReadPixels(void){ return 0; }
void* glReadnPixels(void){ return 0; }
void* glReleaseShaderCompiler(void){ return 0; }
void* glRenderbufferStorage(void){ return 0; }
void* glRotatef(void){ return 0; }
void* glSamplerParameteri(void){ return 0; }
void* glScalef(void){ return 0; }
void* glScissor(void){ return 0; }
void* glShadeModel(void){ return 0; }
void* glShaderBinary(void){ return 0; }
void* glShaderSource(void){ return 0; }
void* glStencilFunc(void){ return 0; }
void* glStencilMask(void){ return 0; }
void* glStencilOp(void){ return 0; }
void* glTexCoord2f(void){ return 0; }
void* glTexCoordPointer(void){ return 0; }
void* glTexImage2D(void){ return 0; }
void* glTexImage3D(void){ return 0; }
void* glTexParameterf(void){ return 0; }
void* glTexParameteri(void){ return 0; }
void* glTexSubImage2D(void){ return 0; }
void* glTranslatef(void){ return 0; }
void* glUniform1f(void){ return 0; }
void* glUniform1fv(void){ return 0; }
void* glUniform1i(void){ return 0; }
void* glUniform2f(void){ return 0; }
void* glUniform2fv(void){ return 0; }
void* glUniform2i(void){ return 0; }
void* glUniform3f(void){ return 0; }
void* glUniform3fv(void){ return 0; }
void* glUniform3i(void){ return 0; }
void* glUniform4f(void){ return 0; }
void* glUniform4fv(void){ return 0; }
void* glUniform4i(void){ return 0; }
void* glUniformBlockBinding(void){ return 0; }
void* glUniformMatrix2fv(void){ return 0; }
void* glUniformMatrix3fv(void){ return 0; }
void* glUniformMatrix4fv(void){ return 0; }
void* glUniformMatrix4x2fv(void){ return 0; }
void* glUniformMatrix4x3fv(void){ return 0; }
void* glUnmapBuffer(void){ return 0; }
void* glUseProgram(void){ return 0; }
void* glValidateProgram(void){ return 0; }
void* glVertex2f(void){ return 0; }
void* glVertex3f(void){ return 0; }
void* glVertexAttribPointer(void){ return 0; }
void* glVertexPointer(void){ return 0; }
void* glViewport(void){ return 0; }
void* glWaitSync(void){ return 0; }
