/* stub surface for libXfixes.so.3 */
void* XFixesShowCursor(void){ return 0; }
void* XFixesHideCursor(void){ return 0; }
void* XFixesCreateRegion(void){ return 0; }
void* XFixesDestroyRegion(void){ return 0; }
void* XFixesSetRegion(void){ return 0; }
void* XFixesCopyRegion(void){ return 0; }
void* XFixesUnionRegion(void){ return 0; }
void* XFixesIntersectRegion(void){ return 0; }
void* XFixesSubtractRegion(void){ return 0; }
void* XFixesInvertRegion(void){ return 0; }
void* XFixesTranslateRegion(void){ return 0; }
void* XFixesRegionExtents(void){ return 0; }
void* XFixesCreateCursorFromName(void){ return 0; }
void* XFixesChangeCursor(void){ return 0; }
void* XFixesSetCursorName(void){ return 0; }
void* XFixesGetCursorName(void){ return 0; }
void* XFixesQueryExtension(void){ return 0; }
void* XFixesQueryVersion(void){ return 0; }
void* XFixesExpandRegion(void){ return 0; }
void* XFixesFetchRegion(void){ return 0; }
void* XFixesSetGCClipRegion(void){ return 0; }
void* XFixesSetWindowShapeRegion(void){ return 0; }
void* XFixesSetPictureClipRegion(void){ return 0; }
void* XFixesSelectCursorInput(void){ return 0; }
void* XFixesGetCursorImage(void){ return 0; }
void* XFixesCreatePointerBarrier(void){ return 0; }
void* XFixesDestroyPointerBarrier(void){ return 0; }
