/* stub surface for libxkbcommon.so.0 */
void* xkb_context_new(void){ return 0; }
void* xkb_context_unref(void){ return 0; }
void* xkb_context_set_log_level(void){ return 0; }
void* xkb_context_set_log_fn(void){ return 0; }
void* xkb_keymap_new_from_string(void){ return 0; }
void* xkb_keymap_new_from_names(void){ return 0; }
void* xkb_keymap_new_from_file(void){ return 0; }
void* xkb_keymap_unref(void){ return 0; }
void* xkb_keymap_key_get_syms_by_level(void){ return 0; }
void* xkb_state_new(void){ return 0; }
void* xkb_state_unref(void){ return 0; }
void* xkb_state_update_key(void){ return 0; }
void* xkb_state_update_mask(void){ return 0; }
void* xkb_state_key_get_syms(void){ return 0; }
void* xkb_state_key_get_utf8(void){ return 0; }
void* xkb_state_mod_index_is_consumed(void){ return 0; }
void* xkb_keymap_get_as_string(void){ return 0; }
void* xkb_keymap_mod_get_index(void){ return 0; }
void* xkb_keymap_led_get_index(void){ return 0; }
void* xkb_compose_table_new_from_locale(void){ return 0; }
void* xkb_compose_state_new(void){ return 0; }
void* xkb_compose_state_feed(void){ return 0; }
void* xkb_compose_state_get_status(void){ return 0; }
void* xkb_utf32_to_utf8(void){ return 0; }
void* xkb_keysym_to_utf8(void){ return 0; }
void* xkb_keysym_from_name(void){ return 0; }
void* xkb_keymap_num_mods(void){ return 0; }
void* xkb_state_serialize_mods(void){ return 0; }
void* xkb_state_serialize_layout(void){ return 0; }
