/* stub surface for libXi.so.6 */
void* XIQueryVersion(void){ return 0; }
void* XIQueryDevice(void){ return 0; }
void* XIFreeDeviceInfo(void){ return 0; }
void* XIOpenDevice(void){ return 0; }
void* XICloseDevice(void){ return 0; }
void* XISelectEvents(void){ return 0; }
void* XIAllowEvents(void){ return 0; }
void* XIGetSelectedEvents(void){ return 0; }
void* XIGrabDevice(void){ return 0; }
void* XIUngrabDevice(void){ return 0; }
void* XIChangeCursor(void){ return 0; }
void* XISetClientPointer(void){ return 0; }
void* XIGetClientPointer(void){ return 0; }
void* XIWarpPointer(void){ return 0; }
void* XIChangeHierarchy(void){ return 0; }
void* XIGetDeviceFocus(void){ return 0; }
void* XIEventToXI2(void){ return 0; }
void* XIQueryPointer(void){ return 0; }
void* XIWarpDevice(void){ return 0; }
void* XIGetDeviceProperty(void){ return 0; }
void* XISetDeviceProperty(void){ return 0; }
void* XIGetProperty(void){ return 0; }
void* XIChangeProperty(void){ return 0; }
void* XIFreeEventData(void){ return 0; }
void* XIGetDeviceState(void){ return 0; }
void* XIListProperties(void){ return 0; }
void* XIGetMotionEvents(void){ return 0; }
