/* stub surface for libXxf86vm.so.1 */
void* XF86VidModeQueryExtension(void){ return 0; }
void* XF86VidModeQueryVersion(void){ return 0; }
void* XF86VidModeGetAllModeLines(void){ return 0; }
void* XF86VidModeGetModeLine(void){ return 0; }
void* XF86VidModeSwitchToMode(void){ return 0; }
void* XF86VidModeSwitchMode(void){ return 0; }
void* XF86VidModeLockModeSwitch(void){ return 0; }
void* XF86VidModeGetMonitor(void){ return 0; }
void* XF86VidModeGetViewPort(void){ return 0; }
void* XF86VidModeSetViewPort(void){ return 0; }
void* XF86VidModeGetDotClocks(void){ return 0; }
void* XF86VidModeSetGamma(void){ return 0; }
void* XF86VidModeGetGamma(void){ return 0; }
void* XF86VidModeSetGammaRamp(void){ return 0; }
void* XF86VidModeGetGammaRamp(void){ return 0; }
void* XF86VidModeSetPageFlip(void){ return 0; }
void* XF86VidModeGetPageFlip(void){ return 0; }
void* XF86VidModeAddModeLine(void){ return 0; }
void* XF86VidModeDeleteModeLine(void){ return 0; }
void* XF86VidModeValidateModeLine(void){ return 0; }
