void* XOpenDevice(void){ return 0; }
void* XCloseDevice(void){ return 0; }
void* XSetDeviceMode(void){ return 0; }
void* XGetDeviceControl(void){ return 0; }
void* XChangeDeviceControl(void){ return 0; }
void* XGetDeviceMotionEvents(void){ return 0; }
void* XGetSelectedExtensionEvents(void){ return 0; }
void* XSelectExtensionEvent(void){ return 0; }
void* XGetExtensionVersion(void){ return 0; }
void* XListInputDevices(void){ return 0; }
void* XFreeDeviceList(void){ return 0; }
void* XQueryDeviceState(void){ return 0; }
void* XDeviceBell(void){ return 0; }
void* XChangeKeyboardDevice(void){ return 0; }
void* XChangePointerDevice(void){ return 0; }
void* XGetFeedbackControl(void){ return 0; }
void* XChangeFeedbackControl(void){ return 0; }
void* XGetDeviceDontPropagateList(void){ return 0; }
void* XChangeDeviceDontPropagateList(void){ return 0; }
void* XGetDeviceModifierMapping(void){ return 0; }
void* XSetDeviceModifierMapping(void){ return 0; }
void* XGetDeviceKeyMapping(void){ return 0; }
void* XChangeDeviceKeyMapping(void){ return 0; }
void* XGetDeviceButtonMapping(void){ return 0; }
void* XSetDeviceButtonMapping(void){ return 0; }
