/* stub surface for libXi.so.6 */
void* XIQueryVersion(void){ return 0; }
void* XIQueryDevice(void){ return 0; }
void* XIFreeDeviceInfo(void){ return 0; }
void* XIOpenDevice(void){ return 0; }
void* XICloseDevice(void){ return 0; }
void* XISelectEvents(void){ return 0; }
void* XIAllowEvents(void){ return 0; }
void* XIGetSelectedEvents(void){ return 0; }
void* XIGrabDevice(void){ return 0; }
void* XIUngrabDevice(void){ return 0; }
void* XIChangeCursor(void){ return 0; }
void* XISetClientPointer(void){ return 0; }
void* XIGetClientPointer(void){ return 0; }
void* XIWarpPointer(void){ return 0; }
void* XIChangeHierarchy(void){ return 0; }
void* XIGetDeviceFocus(void){ return 0; }
void* XIEventToXI2(void){ return 0; }
void* XIQueryPointer(void){ return 0; }
void* XIWarpDevice(void){ return 0; }
void* XIGetDeviceProperty(void){ return 0; }
void* XISetDeviceProperty(void){ return 0; }
void* XIGetProperty(void){ return 0; }
void* XIChangeProperty(void){ return 0; }
void* XIFreeEventData(void){ return 0; }
void* XIGetDeviceState(void){ return 0; }
void* XIListProperties(void){ return 0; }
void* XIGetMotionEvents(void){ return 0; }
void* XOpenDevice(void){ return 0; }
void* XCloseDevice(void){ return 0; }
void* XSetDeviceMode(void){ return 0; }
void* XGetDeviceControl(void){ return 0; }
void* XChangeDeviceControl(void){ return 0; }
void* XGetDeviceMotionEvents(void){ return 0; }
void* XGetSelectedExtensionEvents(void){ return 0; }
void* XSelectExtensionEvent(void){ return 0; }
void* XGetExtensionVersion(void){ return 0; }
void* XListInputDevices(void){ return 0; }
void* XFreeDeviceList(void){ return 0; }
void* XQueryDeviceState(void){ return 0; }
void* XDeviceBell(void){ return 0; }
void* XChangeKeyboardDevice(void){ return 0; }
void* XChangePointerDevice(void){ return 0; }
void* XGetFeedbackControl(void){ return 0; }
void* XChangeFeedbackControl(void){ return 0; }
void* XGetDeviceDontPropagateList(void){ return 0; }
void* XChangeDeviceDontPropagateList(void){ return 0; }
void* XGetDeviceModifierMapping(void){ return 0; }
void* XSetDeviceModifierMapping(void){ return 0; }
void* XGetDeviceKeyMapping(void){ return 0; }
void* XChangeDeviceKeyMapping(void){ return 0; }
void* XGetDeviceButtonMapping(void){ return 0; }
void* XSetDeviceButtonMapping(void){ return 0; }
void* XFreeDeviceState(void){ return 0; }
void* _XiGetDevicePresenceNotifyEvent(void){ return 0; }
void* XFreeExtensionList(void){ return 0; }
