/* stub surface for libXrender.so.1 */
void* XRenderQueryExtension(void){ return 0; }
void* XRenderQueryVersion(void){ return 0; }
void* XRenderQueryFormats(void){ return 0; }
void* XRenderFindVisualFormat(void){ return 0; }
void* XRenderFindFormat(void){ return 0; }
void* XRenderFindStandardFormat(void){ return 0; }
void* XRenderCreatePicture(void){ return 0; }
void* XRenderChangePicture(void){ return 0; }
void* XRenderSetPictureClipRectangles(void){ return 0; }
void* XRenderSetPictureTransform(void){ return 0; }
void* XRenderComposite(void){ return 0; }
void* XRenderFillRectangle(void){ return 0; }
void* XRenderFillPolygon(void){ return 0; }
void* XRenderTrapezoids(void){ return 0; }
void* XRenderAddTrapezoids(void){ return 0; }
void* XRenderFreePicture(void){ return 0; }
void* XRenderCreateCursor(void){ return 0; }
void* XRenderFreeCursor(void){ return 0; }
void* XRenderCreateLinearGradient(void){ return 0; }
void* XRenderCreateRadialGradient(void){ return 0; }
void* XRenderCreateConicalGradient(void){ return 0; }
void* XRenderCompositeText8(void){ return 0; }
void* XRenderCompositeText16(void){ return 0; }
void* XRenderCompositeText32(void){ return 0; }
void* XRenderCreateGlyphSet(void){ return 0; }
void* XRenderFreeGlyphSet(void){ return 0; }
void* XRenderAddGlyphs(void){ return 0; }
void* XRenderFreeGlyphs(void){ return 0; }
void* XRenderCompositeString8(void){ return 0; }
void* XRenderCompositeString16(void){ return 0; }
void* XRenderCompositeString32(void){ return 0; }
void* XRenderParseColor(void){ return 0; }
void* XRenderQueryFilters(void){ return 0; }
void* XRenderSetFilter(void){ return 0; }
