/* stub surface for libxkbcommon.so.0 */
void* xkb_context_new(void){ return 0; }
void* xkb_context_unref(void){ return 0; }
void* xkb_context_set_log_level(void){ return 0; }
void* xkb_context_set_log_fn(void){ return 0; }
void* xkb_keymap_new_from_string(void){ return 0; }
void* xkb_keymap_new_from_names(void){ return 0; }
void* xkb_keymap_new_from_file(void){ return 0; }
void* xkb_keymap_unref(void){ return 0; }
void* xkb_keymap_key_get_syms_by_level(void){ return 0; }
void* xkb_state_new(void){ return 0; }
void* xkb_state_unref(void){ return 0; }
void* xkb_state_update_key(void){ return 0; }
void* xkb_state_update_mask(void){ return 0; }
void* xkb_state_key_get_syms(void){ return 0; }
void* xkb_state_key_get_utf8(void){ return 0; }
void* xkb_state_mod_index_is_consumed(void){ return 0; }
void* xkb_keymap_get_as_string(void){ return 0; }
void* xkb_keymap_mod_get_index(void){ return 0; }
void* xkb_keymap_led_get_index(void){ return 0; }
void* xkb_compose_table_new_from_locale(void){ return 0; }
void* xkb_compose_state_new(void){ return 0; }
void* xkb_compose_state_feed(void){ return 0; }
void* xkb_compose_state_get_status(void){ return 0; }
void* xkb_utf32_to_utf8(void){ return 0; }
void* xkb_keysym_to_utf8(void){ return 0; }
void* xkb_keysym_from_name(void){ return 0; }
void* xkb_keymap_num_mods(void){ return 0; }
void* xkb_state_serialize_mods(void){ return 0; }
void* xkb_state_serialize_layout(void){ return 0; }
void* xkb_compose_state_reset(void){ return 0; }
void* xkb_compose_state_get_utf8(void){ return 0; }
void* xkb_compose_state_get_one_shot(void){ return 0; }
void* xkb_compose_table_new_from_file(void){ return 0; }
void* xkb_compose_table_ref(void){ return 0; }
void* xkb_compose_table_unref(void){ return 0; }
void* xkb_compose_state_ref(void){ return 0; }
void* xkb_compose_state_unref(void){ return 0; }
void* xkb_compose_state_get_direction(void){ return 0; }
void* xkb_state_key_get_utf32(void){ return 0; }
void* xkb_keymap_new_from_buffer(void){ return 0; }
void* xkb_keymap_key_get_mods_for_level(void){ return 0; }
void* xkb_keymap_num_layouts_for_key(void){ return 0; }
void* xkb_state_layout_index_for_key(void){ return 0; }
void* xkb_state_key_get_layout(void){ return 0; }
void* xkb_state_mod_index_is_consumed2(void){ return 0; }
void* xkb_utf8_to_keysym(void){ return 0; }
void* xkb_keysym_to_utf32(void){ return 0; }
void* xkb_keysym_to_lower(void){ return 0; }
void* xkb_keysym_to_upper(void){ return 0; }
void* xkb_keysym_get_name(void){ return 0; }
void* xkb_context_set_user_data(void){ return 0; }
void* xkb_context_get_user_data(void){ return 0; }
void* xkb_context_include_path_append(void){ return 0; }
void* xkb_context_include_path_append_default(void){ return 0; }
void* xkb_context_include_path_clear(void){ return 0; }
void* xkb_context_include_path_get(void){ return 0; }
void* xkb_context_num_include_paths(void){ return 0; }
void* xkb_context_set_log_priority(void){ return 0; }
void* xkb_keymap_led_get_name(void){ return 0; }
void* xkb_keymap_leds(void){ return 0; }
void* xkb_keymap_mods(void){ return 0; }
void* xkb_keymap_key_repeats(void){ return 0; }
void* xkb_keymap_key_get_syms(void){ return 0; }
void* xkb_state_key_get_one_sym(void){ return 0; }
void* xkb_state_key_get_keysym(void){ return 0; }
void* xkb_state_get_keymap(void){ return 0; }
void* xkb_keymap_ref(void){ return 0; }
void* xkb_state_ref(void){ return 0; }
void* xkb_state_key_get_level(void){ return 0; }
void* xkb_state_num_mods(void){ return 0; }
void* xkb_state_num_layouts(void){ return 0; }
